set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(RISCV_TOOLCHAIN_PREFIX "riscv64-unknown-linux-gnu" CACHE STRING "Cross compiler prefix")

find_program(CMAKE_C_COMPILER NAMES ${RISCV_TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(CMAKE_ASM_COMPILER NAMES ${RISCV_TOOLCHAIN_PREFIX}-gcc REQUIRED)
find_program(CMAKE_AR NAMES ${RISCV_TOOLCHAIN_PREFIX}-ar REQUIRED)
find_program(CMAKE_RANLIB NAMES ${RISCV_TOOLCHAIN_PREFIX}-ranlib REQUIRED)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
